import type {
  Species,
  TriageCategory,
  TriageModifier,
  TriageSymptom,
} from "@/features/marketing/components/triage/types";

export const supportedSpecies: readonly {
  value: Species;
  label: string;
}[] = [
  { value: "dog", label: "Perro" },
  { value: "cat", label: "Gato" },
  { value: "exotic", label: "Exótico" },
] as const;

export const triageCategories: readonly {
  value: TriageCategory;
  label: string;
  description: string;
}[] = [
  {
    value: "general",
    label: "General",
    description: "Cambios generales de ánimo, energía o bienestar.",
  },
  {
    value: "digestive",
    label: "Digestivo",
    description: "Vómito, diarrea, abdomen inflamado o malestar digestivo.",
  },
  {
    value: "respiratory",
    label: "Respiratorio",
    description: "Tos, dificultad para respirar o respiración anormal.",
  },
  {
    value: "neurological",
    label: "Neurológico",
    description: "Convulsiones, desorientación o problemas para moverse.",
  },
  {
    value: "urinary",
    label: "Urinario",
    description: "Dificultad para orinar, dolor o cambios urinarios visibles.",
  },
  {
    value: "trauma",
    label: "Trauma / dolor",
    description: "Golpes, heridas, sangrado o dolor evidente.",
  },
  {
    value: "eyes-skin",
    label: "Ojos / piel",
    description: "Lesiones o molestias visibles en ojos, piel o cara.",
  },
  {
    value: "reproductive",
    label: "Reproductivo",
    description: "Problemas durante gestación, parto o secreciones anormales.",
  },
] as const;

export const triageSymptoms: readonly TriageSymptom[] = [
  {
    id: "difficulty-breathing",
    label: "Dificultad para respirar",
    description: "Respira con esfuerzo, muy rápido o parece faltarle el aire.",
    species: ["dog", "cat", "exotic"],
    categories: ["respiratory", "general"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "open-mouth-breathing",
    label: "Respiración con boca abierta",
    description: "Respira con la boca abierta sin estar haciendo ejercicio.",
    species: ["dog", "cat", "exotic"],
    categories: ["respiratory"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "purple-gums",
    label: "Encías moradas o muy azuladas",
    description: "Las encías se ven moradas, azuladas o muy oscuras.",
    species: ["dog", "cat", "exotic"],
    categories: ["respiratory", "general"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "seizures",
    label: "Convulsiones",
    description: "Tiene sacudidas involuntarias o episodios repentinos.",
    species: ["dog", "cat", "exotic"],
    categories: ["neurological"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "unconscious",
    label: "Está inconsciente o no responde",
    description: "No reacciona o parece desvanecido.",
    species: ["dog", "cat", "exotic"],
    categories: ["general", "neurological", "trauma"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "heavy-bleeding",
    label: "Sangrado abundante",
    description: "La sangre sale en cantidad o no se detiene.",
    species: ["dog", "cat", "exotic"],
    categories: ["trauma", "reproductive"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "cannot-urinate",
    label: "No puede orinar",
    description: "Hace esfuerzo, llora o intenta orinar sin lograrlo.",
    species: ["dog", "cat", "exotic"],
    categories: ["urinary"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "hit-by-car",
    label: "Fue atropellado o sufrió un golpe fuerte",
    description: "Tuvo un accidente importante o un golpe severo.",
    species: ["dog", "cat", "exotic"],
    categories: ["trauma", "general"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "painful-bloated-abdomen",
    label: "Abdomen muy distendido con dolor",
    description: "El abdomen se ve muy inflamado y le molesta al tocarlo.",
    species: ["dog", "cat", "exotic"],
    categories: ["digestive", "general"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "protruding-eye",
    label: "Ojo salido o muy desplazado",
    description: "El ojo parece fuera de su lugar o muy expuesto.",
    species: ["dog", "cat", "exotic"],
    categories: ["eyes-skin"],
    score: 10,
    emergencyOverride: true,
  },
  {
    id: "repeated-vomiting",
    label: "Vómito repetido",
    description: "Ha vomitado varias veces en poco tiempo.",
    species: ["dog", "cat", "exotic"],
    categories: ["digestive"],
    score: 3,
  },
  {
    id: "continuous-diarrhea",
    label: "Diarrea continua",
    description: "Tiene evacuaciones muy frecuentes o muy líquidas.",
    species: ["dog", "cat", "exotic"],
    categories: ["digestive"],
    score: 3,
  },
  {
    id: "won't-eat",
    label: "No quiere comer",
    description: "Rechaza su alimento o perdió el apetito.",
    species: ["dog", "cat", "exotic"],
    categories: ["general", "digestive"],
    score: 2,
  },
  {
    id: "very-tired",
    label: "Se ve muy decaído",
    description: "Tiene menos energía de lo normal o se ve muy apagado.",
    species: ["dog", "cat", "exotic"],
    categories: ["general"],
    score: 2,
  },
  {
    id: "coughing",
    label: "Tose con frecuencia",
    description: "Tiene tos repetida o le cuesta recuperarse después de toser.",
    species: ["dog", "cat", "exotic"],
    categories: ["respiratory"],
    score: 3,
  },
  {
    id: "nasal-discharge",
    label: "Tiene moco o secreción nasal",
    description: "Sale secreción por la nariz o respira raro.",
    species: ["dog", "cat", "exotic"],
    categories: ["respiratory"],
    score: 2,
  },
  {
    id: "disoriented",
    label: "Está desorientado o camina raro",
    description: "Se tambalea, parece confundido o pierde equilibrio.",
    species: ["dog", "cat", "exotic"],
    categories: ["neurological", "general"],
    score: 4,
  },
  {
    id: "pain-when-urinating",
    label: "Le duele al orinar",
    description: "Hace esfuerzo, se queja o tarda mucho para orinar.",
    species: ["dog", "cat", "exotic"],
    categories: ["urinary"],
    score: 4,
  },
  {
    id: "limping-or-pain",
    label: "Cojea o muestra dolor evidente",
    description: "Le cuesta caminar o evita apoyarse.",
    species: ["dog", "cat", "exotic"],
    categories: ["trauma", "general"],
    score: 3,
  },
  {
    id: "wound-or-swelling",
    label: "Tiene herida o inflamación visible",
    description: "Hay una lesión abierta o una zona muy inflamada.",
    species: ["dog", "cat", "exotic"],
    categories: ["trauma", "eyes-skin"],
    score: 3,
  },
  {
    id: "red-painful-eye",
    label: "Ojo rojo o muy doloroso",
    description: "No quiere abrir el ojo o le molesta la luz.",
    species: ["dog", "cat", "exotic"],
    categories: ["eyes-skin"],
    score: 4,
  },
  {
    id: "intense-itching",
    label: "Comezón intensa o piel muy irritada",
    description: "Se rasca mucho o la piel se ve muy enrojecida.",
    species: ["dog", "cat", "exotic"],
    categories: ["eyes-skin"],
    score: 2,
  },
  {
    id: "pregnancy-labor-problem",
    label: "Problema durante embarazo o parto",
    description: "Tiene contracciones sin avance, dolor o sangrado preocupante.",
    species: ["dog", "cat", "exotic"],
    categories: ["reproductive"],
    score: 5,
  },
  {
    id: "abnormal-discharge",
    label: "Secreción anormal",
    description: "Tiene flujo con mal olor, sangre o aspecto preocupante.",
    species: ["dog", "cat", "exotic"],
    categories: ["reproductive", "urinary"],
    score: 3,
  },
] as const;

export const triageModifiers: readonly TriageModifier[] = [
  {
    id: "started-suddenly",
    label: "Comenzó de repente",
    description: "El problema apareció de forma súbita.",
    score: 1,
  },
  {
    id: "getting-worse-fast",
    label: "Está empeorando rápido",
    description: "Los signos se están intensificando en poco tiempo.",
    score: 2,
  },
  {
    id: "intense-pain",
    label: "Parece tener dolor intenso",
    description: "Llora, jadea, se queja o no se deja tocar.",
    score: 2,
  },
  {
    id: "cannot-eat-drink",
    label: "No puede comer o tomar agua",
    description: "No logra comer, beber o lo rechaza por completo.",
    score: 2,
  },
  {
    id: "very-young-or-old",
    label: "Es muy pequeño o de edad avanzada",
    description: "Cachorro, gatito, ejemplar muy joven o geriátrico.",
    score: 1,
  },
] as const;
